### PR TITLE
Optimized runtime speed and updated development dependencies

### PR DESCRIPTION
**Pull request by Havunen**
Hi!

I was looking at Rollup build performance and found this module consumes a lot of memory and CPU time. I couldn't optimize the memory consumption and only changes that had any impact on performance are on this PR.

1 - I cached `mappings.length` to `len` variable (.5s diff)
2 - I changed type of array to Int8Array which had biggest impact (4-5s diff)

Total time of rollup build in our application:
```
Before:
67.107s
67.535s
68.158s
68.301s
70.307s

After:
63.797s
65.111s
65.029s
65.675s
63.914s
```

### CODE REVIEW

**Comment by Havunen** [comment]
What I tried:
Changed if else to switch
Inlined charsToInteger 
Tried moving allocation of empty segment inside if branch, which had negative impact for some strange reason.

**Comment by Rich-Harris** [comment]
Fantastic, thank you! Released 1.4.2

**Comment by Havunen** [comment]
I noticed some tests fail in rollup repository if it updates this dependency, I don't know yet why those tests fail. Maybe it has something to do with the type change of Segment

**Comment by Havunen** [comment]
Seems like Int16 passes the tests, I need to investigate more what is the root cause and fix it / PR test here

**Comment by Havunen** [comment]
I have identified the issue and will open new PR with added test case

**Pull request merged**
